#!/usr/bin/env bash
# Kills process

clean_up () {
    rm /var/run/myscript.pid
    exit
}
echo 'prep -f "bash ./100-process_and_pid_file"' > /var/run/myscript.pid
trap clean_up 'echo "I hate the kill command"' SIGTERM
trap clean_up 'echo "Y U no love me?!"' SIGINT

while [ 1 ];
do
    echo "To infinity and beyond"
done
