#!/usr/bin/env bash
# Kills process

clean_up () {
    rm  /var/run/myscript.pid
    exit
}

trap 'echo "I hate the kill command"; clean_up' SIGTERM
trap 'echo "Y U no love me?!"; clean_up' SIGINT

echo $$ >> /var/run/myscript.pid
while true;
do
    echo "To infinity and beyond"
done
