#!/usr/bin/env bash
# Manages process

if [ "$#" -eq 1 ]
then
    if [ "$1" == "start" ];
    then
        ./manage_my_process&
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"
    fi

    if [  "$1" == "stop" ];
    then
        pkill -15 -f "bash ./manage_my_process"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
    fi

    if [ "$1" == "restart" ];
    then
        pkill -15 -f "bash ./manage_my_process"
	rm /var/run/my_process.pid
	./manage_my_process&
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process restarted"
    fi
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
