#!/usr/bin/env bash
# Edits the ip adresses of localhost and facebook.com in /etc/hosts
cp /etc/hosts ~/hosts.new
sed -i '/\blocalhost/s/*./127.0.0.2\tlocalhost/' ~/hosts.new
sed -i '/\bfacebook.com/s/*./8.8.8.8\tfacebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
