#!/usr/bin/env bash
# Edits the ip adresses of localhost and facebook.com in /etc/hosts
cp /etc/hosts ~/hosts.new
sed -i '/[[:space:]]*localhost/s/.*/127.0.0.2\tlocalhost/' ~/hosts.new
echo '8.8.8.8\tfacebook.com' >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts

