#!/usr/bin/env bash
# Getting apache to run and to return a page containing Hello Holberton when querying the root of it.
apt-get update
apt-get install apache2 -y
service apache2 start
cat "Hello Holberton" > /var/www/html/index.html
